INSERT INTO public.helm_catalog_sections (catalog_key, section_key, title, description, sort_order, resolve)
VALUES
('curated_v1', 'istio', 'Istio', 'Official Istio charts (base, istiod, gateway, ambient mesh, CNI, ztunnel). Data from Artifact Hub.', 0, '{"type":"search_filter","ts_query":"istio","repo_url_contains":"istio-release.storage.googleapis.com","chart_order":["base","istiod","gateway","ambient","cni","ztunnel","istiod-remote"]}'::jsonb),
('curated_v1', 'kyverno', 'Kyverno', 'Policy engine for Kubernetes.', 1, '{"type":"search_pick","ts_query":"kyverno","chart_name":"kyverno","prefer_repo_name":"kyverno","max":1}'::jsonb),
('curated_v1', 'velero', 'Velero', 'Cluster backup and restore (VMware Tanzu chart when available).', 2, '{"type":"search_pick","ts_query":"velero","chart_name":"velero","repo_url_contains":"vmware-tanzu.github.io","max":1}'::jsonb),
('curated_v1', 'valkey', 'Valkey', 'Redis-compatible in-memory store. Multiple publishers on Artifact Hub.', 3, '{"type":"search_pick","ts_query":"valkey","chart_name":"valkey","chart_names":["valkey","valkey-cluster"],"max":4}'::jsonb),
('curated_v1', 'redis', 'Redis', 'Common Redis Helm charts (Bitnami and others).', 4, '{"type":"search_pick","ts_query":"redis","chart_names":["redis","redis-cluster"],"repo_url_contains":"bitnami","max":2}'::jsonb),
('curated_v1', 'cert-manager', 'cert-manager', 'Automated TLS certificates for Kubernetes (ACME, private CAs).', 5, '{"type":"exact","repo":"cert-manager","chart":"cert-manager"}'::jsonb),
('curated_v1', 'coredns', 'CoreDNS', 'DNS for Kubernetes clusters and related add-ons.', 6, '{"type":"search_pick","ts_query":"coredns","chart_name":"coredns","prefer_repo_name":"coredns","max":2}'::jsonb),
('curated_v1', 'node-local-dns', 'Node-local DNS cache', 'Node-local DNS caching for lower latency and softer load on cluster DNS (node-local-dns).', 7, '{"type":"search_pick","ts_query":"node-local-dns","chart_name":"node-local-dns","max":3}'::jsonb),
('curated_v1', 'argo-cd', 'Argo CD', 'Declarative GitOps continuous delivery for Kubernetes (Argo Project).', 8, '{"type":"exact","repo":"argo","chart":"argo-cd"}'::jsonb),
('curated_v1', 'argo-workflows', 'Argo Workflows', 'Container-native workflow engine for Kubernetes (DAGs, steps, artifacts).', 9, '{"type":"exact","repo":"argo","chart":"argo-workflows"}'::jsonb),
('curated_v1', 'argo-rollouts', 'Argo Rollouts', 'Progressive delivery (canary, blue/green, experiments) for Kubernetes workloads.', 10, '{"type":"exact","repo":"argo","chart":"argo-rollouts"}'::jsonb),
('curated_v1', 'flux2', 'Flux', 'GitOps toolkit: sync manifests and Helm releases from Git (community bootstrap chart).', 11, '{"type":"exact","repo":"fluxcd-community","chart":"flux2"}'::jsonb),
('curated_v1', 'flagger', 'Flagger', 'Progressive delivery operator (canary, A/B, Blue/Green) often paired with service mesh or ingress.', 12, '{"type":"exact","repo":"flagger","chart":"flagger"}'::jsonb),
('curated_v1', 'linkerd', 'Linkerd', 'Ultralight service mesh (install CRDs, then control plane; optional viz from Buoyant charts).', 13, '{"type":"search_filter","ts_query":"linkerd","repo_url_contains":"helm.linkerd.io","chart_order":["linkerd-crds","linkerd-control-plane","linkerd-viz"]}'::jsonb),
('curated_v1', 'kube-prometheus-stack', 'kube-prometheus-stack', 'Prometheus, Grafana, Alertmanager and common exporters as one chart (prometheus-operator).', 14, '{"type":"exact","repo":"prometheus-community","chart":"kube-prometheus-stack"}'::jsonb),
('curated_v1', 'ingress-nginx', 'ingress-nginx', 'Ingress controller for NGINX, widely used for HTTP(S) routing into the cluster.', 15, '{"type":"exact","repo":"ingress-nginx","chart":"ingress-nginx"}'::jsonb),
('curated_v1', 'traefik', 'Traefik', 'Edge proxy and ingress controller with dynamic configuration.', 16, '{"type":"exact","repo":"traefik","chart":"traefik"}'::jsonb),
('curated_v1', 'metallb', 'MetalLB', 'Bare-metal load-balancer implementation using standard routing protocols.', 17, '{"type":"exact","repo":"metallb","chart":"metallb"}'::jsonb),
('curated_v1', 'cilium', 'Cilium', 'eBPF-powered networking, observability, and security (CNI, mesh, egress, etc.).', 18, '{"type":"exact","repo":"cilium","chart":"cilium"}'::jsonb),
('curated_v1', 'external-dns', 'ExternalDNS', 'Syncs DNS records with cloud providers from Services and Ingresses (Kubernetes SIGs chart).', 19, '{"type":"search_pick","ts_query":"external-dns","chart_name":"external-dns","repo_url_contains":"kubernetes-sigs.github.io/external-dns","max":1}'::jsonb),
('curated_v1', 'metrics-server', 'metrics-server', 'Cluster-wide aggregator of resource metrics (CPU/memory) for kubectl top and HPA.', 20, '{"type":"exact","repo":"metrics-server","chart":"metrics-server"}'::jsonb),
('curated_v1', 'external-secrets', 'External Secrets Operator', 'Sync secrets from external vaults (AWS, GCP, Vault, etc.) into Kubernetes Secrets.', 21, '{"type":"exact","repo":"external-secrets-operator","chart":"external-secrets"}'::jsonb),
('curated_v1', 'sealed-secrets', 'Sealed Secrets', 'Encrypt Secrets into SealedSecret resources safe to store in Git.', 22, '{"type":"exact","repo":"bitnami-labs","chart":"sealed-secrets"}'::jsonb),
('curated_v1', 'crossplane', 'Crossplane', 'Control plane to provision cloud APIs and infrastructure from Kubernetes (XRDs, compositions).', 23, '{"type":"exact","repo":"crossplane","chart":"crossplane"}'::jsonb),
('curated_v1', 'keda', 'KEDA', 'Event-driven autoscaling for Deployments, Jobs, and custom metrics.', 24, '{"type":"exact","repo":"kedacore","chart":"keda"}'::jsonb),
('curated_v1', 'vault', 'Vault', 'HashiCorp Vault on Kubernetes (secrets, encryption, PKI).', 25, '{"type":"exact","repo":"hashicorp","chart":"vault"}'::jsonb),
('curated_v1', 'minio', 'MinIO', 'S3-compatible object storage for Kubernetes.', 26, '{"type":"exact","repo":"minio","chart":"minio"}'::jsonb),
('curated_v1', 'longhorn', 'Longhorn', 'Distributed block storage for Kubernetes (CNCF).', 27, '{"type":"exact","repo":"longhorn","chart":"longhorn"}'::jsonb),
('curated_v1', 'rook-ceph', 'Rook Ceph', 'Ceph storage orchestrated by the Rook operator (block, file, object).', 28, '{"type":"exact","repo":"rook","chart":"rook-ceph"}'::jsonb),
('curated_v1', 'harbor', 'Harbor', 'Cloud native registry: OCI artifacts, signing, scanning (CNCF).', 29, '{"type":"exact","repo":"harbor","chart":"harbor"}'::jsonb),
('curated_v1', 'jaeger', 'Jaeger', 'Distributed tracing backend (OpenTelemetry and Jaeger clients).', 30, '{"type":"exact","repo":"jaegertracing","chart":"jaeger"}'::jsonb),
('curated_v1', 'loki', 'Grafana Loki', 'Horizontally scalable log aggregation inspired by Prometheus labels.', 31, '{"type":"exact","repo":"grafana","chart":"loki"}'::jsonb),
('curated_v1', 'tempo', 'Grafana Tempo', 'High-scale distributed tracing backend, often paired with Grafana.', 32, '{"type":"exact","repo":"grafana","chart":"tempo"}'::jsonb),
('curated_v1', 'strimzi-kafka', 'Strimzi Kafka', 'Apache Kafka on Kubernetes via the Strimzi operator.', 33, '{"type":"exact","repo":"strimzi","chart":"strimzi-kafka-operator"}'::jsonb),
('curated_v1', 'opentelemetry-operator', 'OpenTelemetry Operator', 'Manage OpenTelemetry collectors and instrumentation on Kubernetes.', 34, '{"type":"exact","repo":"opentelemetry-helm","chart":"opentelemetry-operator"}'::jsonb),
('curated_v1', 'kong', 'Kong', 'API gateway and ingress built on Kong Gateway.', 35, '{"type":"exact","repo":"kong","chart":"kong"}'::jsonb),
('curated_v1', 'aws-load-balancer-controller', 'AWS Load Balancer Controller', 'AWS ELB integration for Ingress and Service type LoadBalancer on EKS.', 36, '{"type":"exact","repo":"aws","chart":"aws-load-balancer-controller"}'::jsonb),
('curated_v1', 'cloudnative-pg', 'CloudNativePG', 'PostgreSQL operator for high availability clusters on Kubernetes.', 37, '{"type":"exact","repo":"cloudnative-pg","chart":"cloudnative-pg"}'::jsonb),
('curated_v1', 'reloader', 'Reloader', 'Watch ConfigMaps and Secrets and roll pods when linked data changes.', 38, '{"type":"exact","repo":"stakater","chart":"reloader"}'::jsonb)
ON CONFLICT (catalog_key, section_key) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  sort_order = EXCLUDED.sort_order,
  resolve = EXCLUDED.resolve,
  updated_at = now();
